spring:
  application:
    name: NauJava_hw

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    show-sql: true
    open-in-view: false

  data:
    rest:
      base-path: /api

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"

app:
  name: NauJava Transaction Manager
  version: 1.0.0

admin:
  default:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}